name: Min Nguen
favicon: null
layout_spectrum: 0.825190878007561
typography_spectrum: 0.5181370431091636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9728150889277458
  lightness: 0.2803553787525743
  saturation: 0.10189101099967957
  rhythmicContrast: 0.7850461569614708
purpose: []
