name: Min Nguen
favicon: null
layout_spectrum: 0.7795
typography_spectrum: 0.4101
title: CONCEPT ARTIST
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13181b'
    - '#f8c255'
    - '#c34751'
    - '#f3f6ed'
    - '#c58697'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
